import { useMemo } from "react";
import { calculateIndentStyles } from "@/lib/utils/styleHelpers";
import { IBoxProps } from "./Box.types";

function useBoxProps({
  m,
  mt,
  mr,
  mb,
  ml,
  mx,
  my,
  p,
  pb,
  pl,
  pr,
  pt,
  px,
  py,
  w,
  hMax,
  hMin,
  wMax,
  position,
  top,
  bottom,
  left,
  right,
  display,
  wMin,
  paper,
  h,
  br,
  flex,
  zIndex,
  elevation,
  ...otherProps
}: IBoxProps) {
  const indentStyles = useMemo(
    () =>
      calculateIndentStyles({
        display,
        top,
        bottom,
        insetInlineStart: left,
        insetInlineEnd: right,
        position,
        margin: m,
        marginRight: mr,
        marginLeft: ml,
        marginTop: mt,
        marginBottom: mb,
        marginInline: mx,
        marginBlock: my,
        padding: p,
        paddingRight: pr,
        paddingLeft: pl,
        paddingTop: pt,
        paddingBottom: pb,
        paddingInline: px,
        paddingBlock: py,
        width: w,
        maxWidth: wMax,
        minWidth: wMin,
        height: h,
        maxHeight: hMax,
        minHeight: hMin,
        zIndex: zIndex,
        flex: flex,
      }),
    [
      display,
      top,
      bottom,
      left,
      right,
      position,
      mr,
      mx,
      mb,
      my,
      p,
      py,
      px,
      pt,
      pb,
      wMax,
      wMin,
      hMax,
      w,
      m,
      mt,
      ml,
      pl,
      pr,
      h,
      hMin,
      zIndex,
      flex,
    ]
  );
  return {
    indentStyles: { ...indentStyles },
    otherProps,
  };
}
export default useBoxProps;
